/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.senoracalculadora;

import javax.swing.*;
import javax.swing.border.LineBorder;
import java.awt.*;
import static java.awt.Font.PLAIN;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.Locale;

/**
 *
 * @author DPDAN
 */
public class Cientifica extends javax.swing.JPanel {

    /**
     * Creates new form cientifica
     */
    JLabel displayC;
    int numBotones = 18;
    //Array de botones para números y operaciones
    Boton botones[] = new Boton[numBotones];
    Boton botonCientifico;
    //Array de strings para las etiquetas de los botones
    String textoBotones[] = {"Resultado", "N" , "7", "8", "9", "/", "4", "5", "6", "*", "1", "2", "3", "-", "C", "0", ".", "+"};
    //Array de posiciones en X de cada botón
    int xBotones[] = {15 , 15, 15, 80, 145, 210, 15, 80, 145, 210, 15, 80, 145, 210, 15, 80, 145, 210};
    //Array de posiciones en Y de cada botón
    int yBotones[] = {45, 45, 155, 155, 155, 155, 220, 220, 220, 220, 285, 285, 285, 285, 350, 350, 350, 350};
    //Array de índices del array de botones que corresponden a números (en el órden en el que se pintarán)
    int numerosBotones[] = {14, 9, 10, 11, 5, 6, 7, 1, 2, 3};
    //Array de índices del array de botones que corresponden a operaciones (en el órden en el que se pintarán)
    int[] operacionesBotones = {16, 12, 8, 4};
    //Alto y ancho de cada botón
    int anchoBoton = 50;
    int altoBoton = 50;
    //Para indicar que he terminado de escribir dígitos un número y que voy a añadir el siguiente
    boolean nuevoNumero = true;
    //Para indicar si ya he utilizado el punto decimal en ese número (solo puede haber uno)
    boolean puntoDecimal = false;
    //Para almacenas los resultados parciales y totales de las operaciones realizadas
    double operando1 = 0;
    double operando2 = 0;
    double resultado = 0;
    //Para almacenar el string de la operación realizada (+, -, *, /)
    String operacion = "";

    private void initDisplayC() {

        displayC = new JLabel("0"); //Inicio JLabel
        displayC.setBounds(15, 15, 245, 60); //Posición y dimensiones
        displayC.setOpaque(true); //Para poder darle un color de fondo
        displayC.setBackground(Color.BLACK); //Color de fondo
        displayC.setForeground(Color.GREEN); //Color de fuente
        displayC.setBorder(new LineBorder(Color.DARK_GRAY)); //Borde
        displayC.setFont(new Font("MONOSPACED", PLAIN, 24)); //Fuente
        displayC.setHorizontalAlignment(SwingConstants.RIGHT); //Alineamiento horizontal derecha
        add(displayC); //Añado el JLabel al JFrame
    }

    public Cientifica() {
        initComponents();
        initDisplayC();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(307, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(275, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
